apiVersion: v1
kind: Service
metadata:
  name: picker-service
spec:
  selector:
    app: picker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picker
  template:
    metadata:
      labels:
        app: picker
    spec:
      containers:
        - name: picker
          image: malex5335/algorithm-picker:latest